### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by b00tahead** [mitchlloyd/ember-rails-authentication-example#3]
We're using this method of authentication for our app and I'm having a failing test in the console when I try to run:

```
test('login test - wrong credentials', function(assert) {
  visit('/fbc/s/login');
  fillIn('#inputUsername', 'testuser');
  fillIn('#inputPassword', '123456');
  click('button.btn');
  andThen(() => assert.equal(currentURL(), '/fbc/s/login'));
});
```

The error I get back from the console is:

```
actual: >
  null
message: >
  TypeError: 'undefined' is not an object (evaluating 'response.responseJSON.error')
Log: |
  [object Object]
```

I've tracked down the error to this line in the **app/login/route.js** for failed authentication:

```
var message = response.responseJSON.error;
```

but that's about as far as I've been able to get.

I asked about this in the Ember slack and StackOverflow and both mentioned that I haven't adequately mocked the request. The only thing I can think of is that our login route takes a `:slug` parameter (which in this case is the `fbs` in the url), but I'm unsure of how to pass the slug through in the test.

**Comment by mitchlloyd** [comment]
I'm assuming that you haven't done anything to stub this request to the server. If you're just trying to hit the local server then the error doesn't seem to be returning a JSON response. I would try using a fake server solution like [Mirage](http://www.ember-cli-mirage.com/] to run your tests against).

If you have more information in the StackOverflow question or if you have a repo you can give me I'd be happy to take a look when I have time. I'll close this issue since it doesn't appear that there is an issue with this repo, but we can keep discussing here.
